[pytest]
testpaths = tests
norecursedirs = venv .pytest_cache pytest-cache-files-*
addopts = -q -p no:cacheprovider
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:Warning